appName: Git Commit Viewer
maxCommitsPerCall: 100

# Logging settings.
logging:
  level: DEBUG
  appenders:
    - type: file
      currentLogFilename: ./log/gitviewer.log
      threshold: DEBUG
      archivedLogFilenamePattern: ./log/gitviewer-%d.log
      archivedFileCount: 5
      timeZone: UTC    