appName: Git Commit Viewer
maxCommitsPerCall: 100

# Logging settings.
logging:
  level: DEBUG
  appenders:
    - type: file
      currentLogFilename: ./log/gitviewer.log
      threshold: DEBUG
      archivedLogFilenamePattern: ./log/gitviewer-%d.log
      archivedFileCount: 5
      timeZone: UTC 
database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: changeme
  url: jdbc:postgresql://localhost/postgres
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.hbm2ddl.auto: update
    hibernate.show_sql: false
    hibernate.format_sq: true
